networks:
    default: development
    development:
        gas_limit: max
        gas_buffer: 1
        gas_price: 0
        priority_fee: null
        reverting_tx_gas_limit: false
        default_contract_owner: true
        cmd_settings: null
    live:
        gas_limit: auto
        gas_buffer: 1.1
        gas_price: auto
        priority_fee: null
        reverting_tx_gas_limit: false
        default_contract_owner: false
        explorer:
    kovan:
        gas_limit: max
        gas_buffer: 1
        gas_price: auto
        reverting_tx_gas_limit: max
        default_contract_owner: true
        cmd_settings: null
        explorer: https://api-kovan.etherscan.io/api
    ropsten:
        gas_limit: max
        gas_buffer: 1
        gas_price: auto
        reverting_tx_gas_limit: max
        default_contract_owner: true
        cmd_settings: null
        explorer: https://api-ropsten.etherscan.io/api
compiler:
    evm_version: null
    solc:
        version: null
        optimizer:
            enabled: true
            runs: 200
        remappings: null
    vyper:
        version: 0.2.15

